/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ThaliMenuRouteImport } from './routes/thali-menu'
import { Route as VaranasiGuideRouteImport } from './routes/varanasi-guide'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as RoomsRoomIdRouteImport } from './routes/rooms.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ThaliMenuRoute = ThaliMenuRouteImport.update({
  id: '/thali-menu',
  path: '/thali-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const VaranasiGuideRoute = VaranasiGuideRouteImport.update({
  id: '/varanasi-guide',
  path: '/varanasi-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RoomsRoomIdRoute = RoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => RoomsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/properties': typeof PropertiesRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/thali-menu': typeof ThaliMenuRoute
  '/varanasi-guide': typeof VaranasiGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/properties': typeof PropertiesRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/thali-menu': typeof ThaliMenuRoute
  '/varanasi-guide': typeof VaranasiGuideRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/offers': typeof OffersRoute
  '/partner': typeof PartnerRoute
  '/payment': typeof PaymentRoute
  '/properties': typeof PropertiesRoute
  '/rooms': typeof RoomsRouteWithChildren
  '/thali-menu': typeof ThaliMenuRoute
  '/varanasi-guide': typeof VaranasiGuideRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/rooms/$roomId': typeof RoomsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/auth'
    | '/booking'
    | '/confirmation'
    | '/contact'
    | '/offers'
    | '/partner'
    | '/payment'
    | '/properties'
    | '/rooms'
    | '/thali-menu'
    | '/varanasi-guide'
    | '/admin'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/auth'
    | '/booking'
    | '/confirmation'
    | '/contact'
    | '/offers'
    | '/partner'
    | '/payment'
    | '/properties'
    | '/rooms'
    | '/thali-menu'
    | '/varanasi-guide'
    | '/admin'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/amenities'
    | '/auth'
    | '/booking'
    | '/confirmation'
    | '/contact'
    | '/offers'
    | '/partner'
    | '/payment'
    | '/properties'
    | '/rooms'
    | '/thali-menu'
    | '/varanasi-guide'
    | '/_authenticated/admin'
    | '/rooms/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  OffersRoute: typeof OffersRoute
  PartnerRoute: typeof PartnerRoute
  PaymentRoute: typeof PaymentRoute
  PropertiesRoute: typeof PropertiesRoute
  RoomsRoute: typeof RoomsRouteWithChildren
  ThaliMenuRoute: typeof ThaliMenuRoute
  VaranasiGuideRoute: typeof VaranasiGuideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thali-menu': {
      id: '/thali-menu'
      path: '/thali-menu'
      fullPath: '/thali-menu'
      preLoaderRoute: typeof ThaliMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varanasi-guide': {
      id: '/varanasi-guide'
      path: '/varanasi-guide'
      fullPath: '/varanasi-guide'
      preLoaderRoute: typeof VaranasiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/rooms/$roomId': {
      id: '/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdRouteImport
      parentRoute: typeof RoomsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface RoomsRouteChildren {
  RoomsRoomIdRoute: typeof RoomsRoomIdRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsRoomIdRoute: RoomsRoomIdRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  OffersRoute: OffersRoute,
  PartnerRoute: PartnerRoute,
  PaymentRoute: PaymentRoute,
  PropertiesRoute: PropertiesRoute,
  RoomsRoute: RoomsRouteWithChildren,
  ThaliMenuRoute: ThaliMenuRoute,
  VaranasiGuideRoute: VaranasiGuideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
